name: Selenium E2E Tests

on:
  push:
    branches:
      - main  # Runs on push to the main branch
  schedule:
    - cron: "0 22 * * *"  # Runs daily at 22:00 UTC (Midnight Cairo time)

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Verify Java & Maven Versions
        run: |
          java -version
          mvn -version  # No need to manually install Maven

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Start Xvfb (for Selenium GUI tests)
        run: Xvfb :99 -screen 0 1920x1080x24 &

      - name: Set Display
        run: export DISPLAY=:99

      - name: Run Selenium E2E Tests
        run: mvn test

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: target/surefire-reports/

      - name: Print Logs for Debugging
        if: always()
        run: cat target/surefire-reports/*.txt || echo "No logs found"
